### ISSUE TITLE
Juunior Scrum Master and Helpers Have Rough Draft of Question Survey Ready for the Scrum Meeting :)

### ISSUE THREAD

**Issue by nicolefdz** [nicolefdz/QMB-210-2-Team-1#1]
Please add your question suggestions for the rough draft here :)

**Comment by nicolefdz** [comment]
o	What is your primary reason for joining Greek Life or an academic club?
	 Social networking opportunities
	 Professional development
	 Academic support
	 Leadership opportunities
	 Community service involvement
o	What would be your biggest fear about joining Greek Life or an academic club?
	 Time commitment interfering with studies
	 Not fitting in with the group culture
	 Financial costs
	 Missing out on opportunities from the other option
	 Lack of personal growth
o	What motivates you to stay in Greek Life or an academic club after joining?
	 Close friendships I’ve developed
	 Opportunities to enhance my resume
	 Access to exclusive events
	 Leadership roles and responsibilities
	 Commitment to the organization’s mission
o	What do you believe is the biggest advantage of joining an academic club over Greek Life?
	 Academic support and resources
	 Greater alignment with career goals
	 Less financial commitment
	 Easier balance with academic workload
	 No advantages, I prefer Greek Life
o	What benefits do you believe Greek Life offers that academic clubs do not?
	 Stronger alumni network
	 More social events and opportunities
	 Leadership development
	 Long-term friendships and connections
	 None, I believe academic clubs offer the same benefits

**Comment by Tori-Logan** [comment]
- What is your current grade level?
> Freshman
> Sophomore
> Junior
> Senior

- What is your gender?
> Female
> Male 
> Nonbinary 
> Prefer not to say

- Which college at the University of Tampa are you enrolled in?
> College of Arts and Letters
> College of Natural and Health Sciences
> College of Social Science, Mathematics, and Education  
> Sykes College of Business

- Do you currently live on-campus or off-campus 
> On-campus
> Off-campus

- What extracurricular activities are you currently involved in (if any)at the University of Tampa?
> Greek Life
> Academic Organization
> Sports Team
> Performing Arts
> Other
> None

**Comment by kristinaguatto** [comment]
**- Why would you choose to be in Greek Life over an academic club, or vice versa?**
   Greek life is a closer knit community of friendships
   An academic club allows to students to gain some sort of academic advantage
   One provides students with more opportunities than the other
   I wouldn't choose to be apart of either
   I'd choose to be apart of both, they both have their own unique benefits

**- Why would you encourage someone to join Greek Life or an academic club?**
   To make friends/ create a network at UT
   To gain academic knowledge 
   To explore a hobby/ interest
   I wouldn't encourage anyone to join either

**- Why does Greek Life or an academic club enhance your college experience?**
   It provides more opportunities for students
   It provides a community of people with similar interests
   It looks good on a resume
   It doesn't enhance your college experience
