### ISSUE TITLE
Send out 10 surveys each to friends, classmates, etc. 🌟

### ISSUE THREAD

**Issue by nicolefdz** [nicolefdz/QMB-210-2-Team-1#2]
- Please share the survey with 10 people and then comment when you're done with it, so Jerry can give you credit on this assignment ! 

- This is the link of the survey: https://utampa.az1.qualtrics.com/jfe/form/SV_0ODOGzMTqJIrZK6

FYI: Please be aware that Jerry can see when the same person fills out the survey multiple times due to heir IP address so be minful !

Have a nice day,
Nicole Fdz

**Comment by nicolefdz** [comment]
Done !

**Comment by cruztimbrook** [comment]
done

**Comment by elizsimon** [comment]
done

**Comment by emmazayas29** [comment]
done :)

**Comment by Danielacara** [comment]
done

**Comment by Vanessamonniello** [comment]
done :)

**Comment by Tori-Logan** [comment]
Done!!

**Comment by ellaclapp** [comment]
done.

**Comment by Avamoffitt** [comment]
Done!

**Comment by majawegrowski** [comment]
done

**Comment by kristinaguatto** [comment]
done
