### ISSUE TITLE
Analyze The 2 Questions Assigned And Email It

### ISSUE THREAD

**Issue by nicolefdz** [nicolefdz/QMB-210-2-Team-1#3]
1- Watch Jerrys video to have context of the assignment: https://www.dropbox.com/scl/fi/likhcmo3gx2hzs8tf64bu/ScrumMasterVideoSprint4FA24.zip?rlkey=53sjum76xb2smuydjq60hdvh6&st=mrwc7oyc&dl=0

2-Based of this google sheet document find your question assigment https://docs.google.com/spreadsheets/d/1QA1iukCMXvOwsXqNa6fJXndgvcGKacP4V_PO6YNOx80/edit?gid=0#gid=0.

3- Witht the excel file I emailed, analyze your 2 questions and them email it back.

4- Comment when done !

**Comment by ellaclapp** [comment]
done

**Comment by Vanessamonniello** [comment]
done

**Comment by Tori-Logan** [comment]
done


Victoria Logan

AMA | Executive Vice President

AKPsi | VP of Professionalism

International Business and Marketing | University of Tampa

________________________________

**Comment by cruztimbrook** [comment]
done

**Comment by kristinaguatto** [comment]
done

**Comment by emmazayas29** [comment]
done

**Comment by Danielacara** [comment]
done

**Comment by majawegrowski** [comment]
done

**Comment by elizsimon** [comment]
done

**Comment by Avamoffitt** [comment]
done
